name: Publish to NPM

on:
  push:
    branches: [mainbackup]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: yarn

      - name: Bump versions
        run: yarn beachball bump

      - name: Build
        run: yarn run build

      - name: Reset bump
        run: git checkout -- .

      - name: Set Git Authentication
        run: git config user.email = "erick@metronome.sh" && git config user.name = "Erick Tamayo" && git remote set-url origin https://ericktamayo:${{ secrets.GH_TOKEN }}@github.com/metronome-sh/metronome-sh.git

      - name: Publish to NPM
        run: yarn beachball publish -n ${{ secrets.NPM_TOKEN }} --yes
