name: Publish to NPM

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Set Git Authentication
        run: |
          git config user.email = "erick@metronome.sh"
          git config user.name = "Erick Tamayo"
          git remote set-url origin https://ericktamayo:${{ secrets.GH_TOKEN }}@github.com/metronome-sh/metronome-sh.git

      - name: Changeset Version
        run: |
          npx @changesets/cli version

      - name: Build
        env:
          NODE_ENV: production
        run: pnpm run build

      - name: Publish to npm
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changeset
        run: |
          git add .
          git commit -m "chore: changeset [skip actions]"
          git push
