name: Publish to NPM

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Set Git Authentication
        run: |
          git config user.email = "erick@metronome.sh"
          git config user.name = "Erick Tamayo"
          git remote set-url origin https://ericktamayo:${{ secrets.GH_TOKEN }}@github.com/metronome-sh/metronome-sh.git

      - name: Changeset Version
        run: |
          npx @changesets/cli version
          git add .
          git commit -m "version changeset [skip actions]"

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Rerun pnpm install
        run: pnpm install --no-frozen-lockfile

      - name: Check for pnpm-lock.yaml changes
        id: lockfile-check
        run: |
          echo "LOCKFILE_CHANGED=$(git diff --name-only | grep -q 'pnpm-lock.yaml' && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Push Changes
        if: env.LOCKFILE_CHANGED == 'true'
        run: |
          git add .
          git commit -m "updated pnpm-lock.yaml [skip actions]"
          git push
