name: Publish to NPM

on:
  push:
    branches: [mainbackup]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: pnpm install

      - name: Changeset Version
        run: |
          npx @changesets/cli version
          git add .
          git commit -m "version changeset"

      - name: Build
        run: pnpm run build

      - name: Set Git Authentication
        run: |
          git config user.email = "erick@metronome.sh"
          git config user.name = "Erick Tamayo"
          git remote set-url origin https://ericktamayo:${{ secrets.GH_TOKEN }}@github.com/metronome-sh/metronome-sh.git

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
