name: Tests
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test
